name: Seatronic
favicon: null
layout_spectrum: 0.74695
typography_spectrum: 0.22814675280824304
title: Seatronic - Mini Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4a575f'
    - '#818a8f'
    - '#02b5dd'
    - '#ffffff'
    - '#c7cbcd'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
